name: mbeah_online
description: A portfolio websit for Prince Mbeah Essilfie.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  # animated_text_kit: ^4.2.2
  # carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  # flutter_riverpod: ^2.4.5
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  go_router: ^12.0.1
  google_fonts: ^6.1.0
  photo_view: ^0.14.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - images/
  - icons/
